import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MarketplaceProvider } from "@/components/providers/marketplace";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* T002 — Toaster mounted once at the root layout, above the
            MarketplaceProvider tree. Both /widget and /panel routes share
            this layout, so a single mount covers both surfaces. Per
            ADR-0021, toasts are reserved for cross-cutting failures
            (e.g. blob construction) — no per-action wiring at this stage. */}
        <Toaster />
        <MarketplaceProvider>{children}</MarketplaceProvider>
      </body>
    </html>
  );
}
